[ERROR] 2025-08-09 18:26:02,400 django.request: Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
  File "/home/ken/study/django/todo/accounts/views.py", line 22, in form_valid
    return super().form_valid(form)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 109, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 41, in get_success_url
    return self.get_redirect_url() or self.get_default_redirect_url()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/views.py", line 96, in get_default_redirect_url
    return resolve_url(settings.LOGIN_REDIRECT_URL)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list' not found. 'list' is not a valid view function or pattern name.
[ERROR] 2025-08-09 18:26:45,650 django.request: Internal Server Error: /todo/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
  File "/home/ken/study/django/todo/todo/views/task.py", line 27, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")
[ERROR] 2025-08-09 18:27:20,705 django.request: Internal Server Error: /todo/list
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
  File "/home/ken/study/django/todo/todo/views/task.py", line 27, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")
[ERROR] 2025-08-09 18:27:36,457 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
  File "/home/ken/study/django/todo/todo/views/task.py", line 27, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")
[ERROR] 2025-08-09 18:28:07,128 django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 259, in get
    url = self.get_redirect_url(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 249, in get_redirect_url
    url = reverse(self.pattern_name, args=args, kwargs=kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list' not found. 'list' is not a valid view function or pattern name.
[ERROR] 2025-08-09 18:28:27,504 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 178, in get
    context = self.get_context_data()
  File "/home/ken/study/django/todo/todo/views/task.py", line 27, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 128, in get_context_data
    paginator, page, queryset, is_paginated = self.paginate_queryset(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 73, in paginate_queryset
    page = paginator.page(page_number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 89, in page
    number = self.validate_number(number)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 70, in validate_number
    if number > self.num_pages:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 116, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/paginator.py", line 110, in count
    return c()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in count
    return self.query.get_count(using=self.db)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 644, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 626, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'todo.todo_task' doesn't exist")
[ERROR] 2025-08-09 18:29:45,760 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: todo/task_list.html, todo/task_list.html
[ERROR] 2025-08-09 18:30:15,992 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'scheduler' is not a registered namespace
[ERROR] 2025-08-09 18:31:02,042 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list' not found. 'list' is not a valid view function or pattern name.
[ERROR] 2025-08-10 11:43:10,201 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 327, in render
    return nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'task_detail' not found. 'task_detail' is not a valid view function or pattern name.
[ERROR] 2025-08-10 12:09:39,576 django.request: Internal Server Error: /todo/create/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_invalid(form)
  File "/home/ken/study/django/todo/todo/views/task.py", line 63, in form_invalid
    messages.error("タスクの登録に失敗しました。")
TypeError: error() missing 1 required positional argument: 'message'
[ERROR] 2025-08-10 12:12:01,451 django.request: Internal Server Error: /todo/create/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_invalid(form)
  File "/home/ken/study/django/todo/todo/views/task.py", line 62, in form_invalid
    print(f"Form error: {form.due_date.errors}")
AttributeError: 'TaskForm' object has no attribute 'due_date'
[ERROR] 2025-08-10 14:10:53,093 django.request: Internal Server Error: /admin/todo/task/3/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:11:01,350 django.request: Internal Server Error: /admin/todo/task/3/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:11:17,139 django.request: Internal Server Error: /admin/todo/task/1/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:11:23,082 django.request: Internal Server Error: /admin/todo/task/1/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:12:09,412 django.request: Internal Server Error: /admin/todo/task/3/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:19:16,467 django.request: Internal Server Error: /admin/todo/task/3/delete/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2207, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2242, in _delete_view
    self.log_deletions(request, [obj])
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1018, in log_deletions
    return LogEntry.objects.log_actions(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/contrib/admin/models.py", line 98, in log_actions
    instance.save()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 902, in save
    self.save_base(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1008, in save_base
    updated = self._save_table(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1169, in _save_table
    results = self._do_insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1210, in _do_insert
    return manager._insert(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 76, in execute
    return self.cursor.execute(query, args)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect integer value: 'ef96d246b1a24041861ed4f9992bc383' for column 'user_id' at row 1")
[ERROR] 2025-08-10 14:21:42,791 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' o.priority == "1"' from 'if o.priority == "1"'
[ERROR] 2025-08-10 14:21:55,979 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' o.priority == "1"' from 'if o.priority == "1"'
[ERROR] 2025-08-10 14:25:44,450 django.request: Internal Server Error: /todo/detail/4/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/urls/base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'scheduler' is not a registered namespace
[ERROR] 2025-08-10 14:29:11,084 django.request: Internal Server Error: /todo/delete/4/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: todo/task/confirm_delete.html
[ERROR] 2025-08-10 19:46:25,688 todo.views.task: Task create form invalid errors={'due_date': ['期限は今日以降の日付を指定してください。']}
[ERROR] 2025-08-10 23:19:28,550 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('todo/task/css/list_styles.css')' from 'static('todo/task/css/list_styles.css')'
[ERROR] 2025-08-10 23:20:11,257 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:30:20,413 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/context.py", line 88, in __getitem__
    raise KeyError(key)
KeyError: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 897, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 743, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [obj] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'paginator': <django.core.paginator.Paginator object at 0x7705e31c7670>, 'page_obj': <Page 1 of 1>, 'is_paginated': False, 'object_list': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'tasks': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'view': <todo.views.task.TaskListView object at 0x7705e3b73820>, 'q': '', 'status': 'all', 'sort': 'due_date', 'dir': 'asc', 'today': datetime.date(2025, 8, 10), 'count_all': 2, 'count_open': 2, 'count_done': 0}]
[ERROR] 2025-08-10 23:31:04,856 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/context.py", line 88, in __getitem__
    raise KeyError(key)
KeyError: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 897, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 743, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [obj] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'paginator': <django.core.paginator.Paginator object at 0x7705e3157eb0>, 'page_obj': <Page 1 of 1>, 'is_paginated': False, 'object_list': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'tasks': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'view': <todo.views.task.TaskListView object at 0x7705e286bee0>, 'q': '', 'status': 'all', 'sort': 'due_date', 'dir': 'asc', 'today': datetime.date(2025, 8, 10), 'count_all': 2, 'count_open': 2, 'count_done': 0}]
[ERROR] 2025-08-10 23:31:19,701 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[bit]
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/context.py", line 88, in __getitem__
    raise KeyError(key)
KeyError: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 897, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 907, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 548, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 743, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 854, in resolve
    value = self._resolve_lookup(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 914, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [obj] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'paginator': <django.core.paginator.Paginator object at 0x7936d7ed7070>, 'page_obj': <Page 1 of 1>, 'is_paginated': False, 'object_list': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'tasks': <QuerySet [<Task: test（未完了）>, <Task: test666（未完了）>]>, 'view': <todo.views.task.TaskListView object at 0x7936dc983130>, 'q': '', 'status': 'all', 'sort': 'due_date', 'dir': 'asc', 'today': datetime.date(2025, 8, 10), 'count_all': 2, 'count_open': 2, 'count_done': 0}]
[ERROR] 2025-08-10 23:37:27,249 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 69: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:39:57,979 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 68: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:40:22,128 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 68: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:41:34,641 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 68: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:43:59,710 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 63: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:45:22,764 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 63: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-10 23:51:21,420 django.request: Internal Server Error: /todo/list/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 70: 'endwith', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
[ERROR] 2025-08-11 13:43:34,161 todo.views.task: Task create form invalid errors={'due_date': ['期限は今日以降の日付を指定してください。']}
[ERROR] 2025-08-11 15:19:16,176 django.request: Internal Server Error: /todo/delete/1/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
[ERROR] 2025-08-11 15:19:20,565 django.request: Internal Server Error: /todo/delete/1/
Traceback (most recent call last):
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/ken/study/django/todo/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
